spring.application.name=inventory-service
server.port=8082

# PostgreSQL running in Docker mapped to host port 5433 (to avoid collision if order-service DB uses 5432)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/inventory_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

# Eureka Client Discovery
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}